### ISSUE TITLE
[Feat] 닉네임 설정 뷰 UI 구현

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#10]
## 🔥 Issue 내용
닉네임 적고 중복확인하는 뷰 구현
## ✅ To-do
- [x] textfield와 버튼 2개 구현
- [x] textfield이 활성화되면 버튼 색상 변경
- [x] GUI 디자인 및 레이아웃 적용
