### ISSUE TITLE
[Fix] 닉네임 설정 뷰, 성별 선택 뷰 다음 버튼 QA 수정

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#108]
## 🔥 Issue 내용
중복확인 후 닉네임 다 지웠을 때도 다음 버튼이 활성화되어 있는 문제
생년월일 선택 시 다음 버튼 활성화되는 문제
성별을 선택했다가 지웠을 때도 다음 버튼이 활성화되어 있는 문제
## ✅ To-do
- [x] 중복확인 뷰 다음 버튼 로직 수정
- [x] 생년월일 통과 시 다음 버튼 활성화되도록 수정
- [x] 성별 버튼 비활성화 시 다음 버튼도 비활성화되도록 수정
