### ISSUE TITLE
[Fix] 공원 탐험 성공 시 팝업이 뜨지 않는 문제 해결

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#114]
### 문제 상황: 지도에서 공원 탐험 성공 시 성공 팝업이 뜨지 않음
앱잼 기간 동안 제대로 구현이 되어 있지 않다가, 데모데이날 긴급 패치를 통해 현재 TestFlight에는 해당 기능이 구현돼 있는데,  
현재 main 브랜치에는 구현되어 있지 않는 상황임. 

## ✅ To-do
- [x] 공원 탐험 성공 시 탐험 성공 팝업 뷰 띄우기
- [x] 공원 탐험 성공 팝업에서 홈 화면으로 이동하는 버튼 기능 구현하기
- [x] 공원 탐험 성공 후 홈 화면으로 이동 시 로티 움직이도록 구현
