### ISSUE TITLE
[Fix] QA수정(1차)

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#118]
## ✅ To-do
- [x] 지도 마커 탭 시 배율 조정 해제
- [x] 지도에서 현 위치 버튼 동작 수정 (안드랑 비슷하게 맞추기)
- [x] QR 인증 성공 시 배경 어둡게 설정
