### ISSUE TITLE
[Fix] 닉네임 뷰 1차 싱크

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#125]
## 🔥 Issue 내용
AOS/iOS 닉네임 뷰 1차 싱크 맞추기
## ✅ To-do
- [x] 키보드가 올라왔을 때도 중복확인 클릭 가능하게 적용 필요
- [x] 중복확인 후 유효값이면 중복확인 버튼 비활성화 필요 - 중복확인 통과 후 텍스트 필드 수정 시 다시 중복확인 버튼 활성화
- [x] 중복확인 비활성화 시 레이어 필요
- [x] 자음 안되게 수정
- [x] 영한길이 EUC-KR 16바이트
- [x] 닉네임 형식은 실시간 유효성 검사(중복확인은 버튼)
- [x] 중복확인 클릭 후 중복된 닉네임일 때 중복확인 버튼 비활성화
- [x] 중복확인 후 텍스트필드 수정하면 다음 버튼 비활성화
- [x] 유지보수 용이하게 코드 리팩토링(메소드 추출)
- [x] 디자인 측 색상 변경 적용
