### ISSUE TITLE
[Fix] 나이 뷰 1차 싱크

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#129]
## 🔥 Issue 내용
나이 뷰에서의 AOS/iOS 싱크 수정사항
## ✅ To-do
- [x] 연 유효값 쓰고 다음 텍스트 필드로 넘어갔을 때 오류 메시지 안사라짐 - 사라지게 수정
- [x] 일 오류 시 에러 메시지 뜨게 수정
- [x] 월,일 한 자리수 써도 되게 수정
- [x] 연 1900년부터 현재 시간까지로 수정
- [x] 나이에서 뒤로가기 했을 때 닉네임 다음 버튼 활성화 및 중복 버튼 비활성화(중복 확인 완료된 상태)
- [x] 디자인 변경사항 적용
