### ISSUE TITLE
[Feat] 획득 캐릭터 뷰 UI

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#133]
## 🔥 Issue 내용
마이페이지에서 유저가 "획득 캐릭터"를 눌렀을 때 나오는 뷰의 UI이다.
## ✅ To-do
- [x] 컬렉션뷰와 UIView 구현
- [x] UIView 내 labels와 이미지 생성
- [x] 컬렉션 뷰 내 셀 레이아웃 적용 및 세로 스크롤 구현
- [x] 캐릭터 별 디자인 및 이름 적용
