### ISSUE TITLE
[Feat] 획득 쿠폰  UI

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#142]
## 🔥 Issue 내용
마이페이지에서 "획득 쿠폰"을 눌렀을 때 나타나는 UI 구현
## ✅ To-do
- [ ] 획득 쿠폰 UIView 생성
- [ ] 쿠폰 셀 담긴 컬렉션 뷰 생성
- [ ] 사용 가능/ 사용 완료로 나누기
