### ISSUE TITLE
[Fix] 자잘한 버그 해결 및 수정사항 반영

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#162]
## 🔥 Issue 내용
자잘한 버그들 수정

## ✅ To-do
- [x] 내비게이션이 pop되면서 탭바가 나타날 때, swipe 제스처로 pop 할 경우, pop 애니메이션이 끝나기 전에도 탭바버튼이 눌리는 문제 해결
- [ ] ~지도의 '내 위치 마커' 에서 방향 표시가 없을 때 지도의 북쪽이 위로 가도록 설정~
- [x] 지도에서 '현 지도에서 검색' 버튼의 터치 피드백 적용
- [x] ColorLiteral 및 FontLiteral 적용
  - QuestListView
  - CustomSegmentedControl(폰트)
  - 일부는 스타일가이드에 정해진 색이 없어서 hexCode로 유지
