### ISSUE TITLE
[Fix] QA 수정사항 반영

### ISSUE THREAD

**Issue by Johyerin** [Team-Offroad/Offroad-iOS#180]
## 🔥 Issue 내용
QA 수정사항 반영

## ✅ To-do
- [x] 최근 진행한 퀘스트 수가 커지면 레이아웃이 충돌하는 문제
- [x] 완료 임박 퀘스트 progress bar 버그 해결 (뷰가 표시될 때마다 진한 색 bar의 일부가 나타났다 사라짐)
- [x] 약관 동의 뷰 상세 내용 수정
- [x] Patch 통신 함수 및 DTO 수정
- [x] 캐릭터 선택 무한 캐러셀 버그 수정
- [x] 설정 뷰 각 항목 리다이렉션
- [ ] ...
