### ISSUE TITLE
[Fix] 회원가입 QA 수정사항 반영

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#185]
## ✅ To-do
- [ ] textfield 눌렀을 때 layer 검정으로 변경 요청 -> 검정은 클릭과 텍스트 유무
- [ ] textfield 미입력 후 키보드 내려가면 다시 회색이게 변경
- [ ] textfield 입력 후 다 지웠을 때 textfield에 커서가 있다면 layer 검정이게 변경
- [ ] 하나라도 오류가 있다면 에러메세지 계속 떠 있도록 수정
- [ ] 오류 난 textfield의 layer는 다른 곳을 선택해도 유지되도록 수정
