### ISSUE TITLE
[Fix] QA 수정사항 반영

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#190]
## 🔥 Issue 내용
QA 수정사항을 반영하기 위함입니다. 

## ✅ To-do
- 장소 목록 뷰
  - [ ] ~현재 위치 기반으로 불러오기 때문에, 장소 목록이 없을 경우 피드백 구현~ -> QA 후에 구현
  - [x] 구역(예. 시간이 머무는 마을) 표시 라벨 데이터 받아올 수 있도록 구현 -> empty case는 QA 후에 구현
- 퀘스트 목록 뷰
  - [x] 퀘스트 목록 뷰 상자 크기 개선 (데이터 없을 때에도 상자 크기 유지할 수 있도록)
  - [ ] ~퀘스트 목록 뷰에 컨텐츠 없을 경우 피드백 구현(진행 중 스위치 켰을 경우도 포함)~ -> QA후에 구현
- 쿠폰 상세 뷰
  - 174번 브랜치 머지 후 API 연결할 예정 (다른 브랜치에서 작업 예정)
