### ISSUE TITLE
[Fix] 쿠폰 상세 뷰 UI 개선

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#194]
## 🔥 Issue 내용
쿠폰 상세 뷰의 UI를 개선할 부분이 있어 이를 반영하고자 합니다.

## ✅ To-do
- [x] 기존에 사용되던 팝업 뷰 제거
- [x] 쿠폰 안의 이미지 크기 & 위치 조정
- [x] 사용 방법 텍스트 적힌 라벨 수정
  - 높이 제약 해제
  - numberOfLines 2로 설정한 것 해제
  - setLineSpacing 메서드 사용 코드 삭제
- [x] 사용방법 텍스트 옆의 자물쇠&열쇠 이미지 크기 조정
- [x] 쿠폰 이미지 높이 설정 (iPhone 13 mini에서 세로로 길어 보이는 현상이 있음.
- [x] 각종 곡률반경 Figma 수치에 맞게 재조정
- [x] 점선 뷰 오른쪽 inset 적용되지 않는 문제 해결
