### ISSUE TITLE
[Fix] 각종 버그 수정 및 개선사항 적용

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#197]
## 🔥 Issue 내용
각종 버그 수정 및 개선사항 적용
쓰다 보니 목록이 길어져서, 분류하여 각자 브랜치를 따로 파는 게 더 나을지도...?

## ✅ To-do
- [x] 쿠폰 사용 뷰에서 이미 사용된 쿠폰 셀 비활성화 적용
- [x] 마이페이지의 하단 안전 영역 수정(UIViewController로 되어있던데, 타입을 OffroadTabBarViewController로 변경하기)
- [x] 텍스트필드 안의 글씨 다크모드일 경우 보이지 않는 문제 해결 (쿠폰 사용 팝업)
- [x] ~장소 목록 뷰에서 "전체" 탭 누를 경우, 첫 번째 셀의 가로 길이가 이상하게 보이는 문제 해결(시뮬레이터 한정)~
-> 다른 브랜치에서 이미 해결함
- [x] ~장소 목록 뷰에서 아래로 스크롤하여 새로고침할 경우, 장소 목록이 현재 위치 기준이 아닌 다른 기준으로 보이는 문제 해결~
-> 다른 브랜치에서 이미 해결함
- [x] 아코디언 뷰에서 펼쳐지는 부분의 컨텐츠, 셀이 커지고 작아지는 애니메이션에 보이거나 숨기는 fade-in, fade-out 애니메이션 설정  
-> 애니메이션은 적용 X, 그냥 사라지거나 나타나게만 구현함.
- [x] OFRSegmentedControl의 다른 탭을 누른 즉시 page view controller 안의 컬렉션뷰를 스크롤하면 세그먼트가 바뀌지 않는 문제
- [x] 퀘스트 목록 뷰를 들어갔다 장소 목록 뷰에 들어가면 제스처를 이용한 pop이 불가능한 문제
  - QuestListViewController에서 navigationItem.setHidesBackButton(true, animated: false)를 호출하는 것이 이유
  - gestureRecognizer 관련 코드들도 모두 삭제
- [x] 장소 목록 뷰(를 포함한 다양한 뷰에서)의 스크롤 인디케이터 다크모드에서 흰색으로 보이는 문제
