### ISSUE TITLE
[Feat] CustomSegmentedControl 사용 관련 뷰 UI 개선

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#210]
## 🔥 Issue 내용
CustomSegmentedControl을 사용되는 뷰들에서 전체적으로 UI를 개선하기 위함입니다. 
## ✅ To-do
- [x] 처음 화면에 들어갈 때 underbar가 보이도록 구현하기
- [x] 각 세그먼트를 선택 시, 이를 보여주는 화면이 좌우로 스크롤 되도록 구현
- [x] 세그먼트 선택 뿐만 아니라 손으로 직접 스크롤 했을 때에도 각 화면 사이를 이동할 수 있어야 하며, 이 때 세그먼트도 바뀌도록 구현하기
- [ ] ~세그먼트에 따라서 CustomSegmentedControl의 언더바 위치를 실시간으로 변경할 수 있도록 구현 (스크롤과 underbar가 interactive하도록)~ -> 후순위로 미루기
- [x] 이미 선택된 탭 눌렸을 때 delegate에서 추가 호출되지 않도록 구현
