### ISSUE TITLE
[Feat] 대표캐릭터 선택 전체 적용 api 연결

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#213]
## ✅ To-do
- [ ] 캐릭터 선택 api를 이용하여 '대표 캐릭터 선택하기' 버튼 누르면 전체 적용되도록 구현
- [ ] representativeCharacterId를 통해 CharacterListCell에 대표캐릭터 부분에 뱃지 뜨도록 구현
- [ ] 대표캐릭터 셀 눌렀을 때 버튼 비활성화 되는 것 구현
