### ISSUE TITLE
[Setting] 개발 환경 추가 세팅(.gitignore 등)

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#22]
## 🔥 Issue 내용
협업 중에 여러 에러와 이슈가 생겨, 추가적으로 개발 환경을 세팅하고자 함. 
주요 이슈는 Package.resolved 파일이 자동으로 삭제되는 이슈, 그리고 .DS_Store

## ✅ To-do
- [ ] Package.resolved 파일 삭제 후 .gitignore에 추가
- [ ] .DS_Store 파일 삭제 후 .gitignore에 추가
- [ ] iOS 최소 배포 버전 17 -> 15로 변경하기
