### ISSUE TITLE
각종 버그 수정 및 개선사항 적용

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#221]
## 🔥 Issue 내용
각종 버그 수정 및 개선사항 적용

## ✅ To-do
- [ ] 리프레시 토큰 만료 시, 로그인 화면으로 넘어가지 않는 문제
리프레시 토큰 만료 시 재발급이 안되는걸까?
-> 7일 이상 접속하지 않은 기기(시뮬레이터)에서 발생하는 문제인 듯
-> @Johyerin 담당
- [ ] 피그마 상의 탭바 버튼 아이콘 다운 시 앱에서 이상하게 보이는 문제
  - 일러스트레이터로 열어보니 SVG파일이 이상하게 그려져 있다. 
  - 아마 디자이너분들이 직접 그린 게 아니라 피그마에서 계산해서 나온 아이콘을 벡터 이미지로 변환하는 과정에서 이상해진 것일 수도...?
  -> 직접 그리는 방법이 제일 빠르고 편할 듯...?
- [x] 마이페이지 모든 화면이 스크롤될 수 있도록 변경
  - iPhone 8과 같이 홈 버튼이 있는 기종의 경우 화면 비율이 달라서 스크롤 해야 할 수도 있음. 
  현재는 아래 버튼 영역만 스크롤이 되도록 구현된 상태임.
  - 변경 전에 전체 스크롤이 의도에 맞는지 기획 측에 물어보기
- [x] 획득 칭호 뷰의 컬렉션뷰가 화면 하단 가장자리까지 보이지 않는 문제
