### ISSUE TITLE
[Fix] 2차 QA 수정사항 반영

### ISSUE THREAD

**Issue by Johyerin** [Team-Offroad/Offroad-iOS#238]
## 🔥 Issue 내용
2차 QA 수정사항 반영

## ✅ To-do
- [x] 마이페이지 서버 데이터 로딩
- [x] 마이페이지 레이아웃 수정
- [x] 홈뷰 레이아웃 수정
- [x] 획득 칭호, 설정 뷰 컬뷰 레이아웃 수정
- [x] 공지사항 뷰 외부링크 리다이렉션 로직 추가
- [ ] ...
