### ISSUE TITLE
[Feat] GenderViewController UI 구현

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#25]
## 🔥 Issue 내용
프로필 설정에서 성별을 선택하는 뷰이다.
## ✅ To-do
- [x] 버튼 3개 생성
- [x] 버튼 활성화 시 tintcolor와 backgroundcolor 적용
- [x] 디자인과 레이아웃 적용
- [x] View와 ViewController 책임 분리
