### ISSUE TITLE
[Feat] ChoosingCharacterViewController UI 구현

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#29]
## 🔥 Issue 내용
무한 캐러샐을 통해 캐릭터를 넘기며 선택하는 뷰이다.
## ✅ To-do
- [x] 캐릭터 asset 추가
- [x] labels 열거형으로 구현
- [x] infinite carousel 구현
- [x] 디자인 및 레이아웃 적용
- [x] View와 ViewController 책임 분리
- [x] 화살표 asset 추가 및 기능 구현
