### ISSUE TITLE
[Fix] 버그 해결, 수정

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#296]
## ✅ To-do
- [x] 채팅 로그 뷰에서 채팅 로그 뷰가 하나도 없을 시 키보드를 내릴 수 없는 현상(컬렉션뷰에 panGesture가 감지되어야 하는데, 빈 컬렉션뷰인 경우, panGesture를 감지하지 못하는 것 같음.)
- [x] 장소 툴팁 배경 이미지 변경하기
- [x] 퀘스트 목록 뷰 진입 시 스위치 기본값 On 으로 변경
[채널톡 의논 결과](https://desk.channel.io/z3vne/threads/groups/2_기획클라-409134/673a286acddb6b26701f/673a286acddb6b26701f)
- [x] 네트워크 끊어진 상태에서 CharacterDetailView로 진입 후(현재 빈 화면인 상태) 네트워크 다시 연결되면 네트워크 연결 상태를 확인하라는 토스트가 뜨는 문제
- [x] 캐릭터 선톡이 왔을 때, 홈 화면의 채팅 버튼을 누를 경우 대응
