### ISSUE TITLE
[Chore] 자잘한 UI 개선

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#333]
## 🔥 Issue 내용
자잘한 UI 개선용.
확인 시 추가 가능
## ✅ To-do
- [x] 캐릭터 상세 뷰에서 캐릭터 아이콘 이미지 제거
- [x] 획득 캐릭터 목록 뷰에서 체크표시 아이콘 비율이 맞지 않는 것처럼 보임.(정방형이어야 함.)
- [x] 획득 캐릭터 목록 뷰에서 아이콘 변경(리브랜딩된 색의 이미지로 변경)
- [x] 획득 쿠폰 목록 뷰에서 segmentedControl과 collectionView 사이의 separator가 없음.
- [x] 캐릭터 상세 뷰에서 모션의 배경이 되는 부분 색 흰색으로 변경(지금은 아주 아주 약간 회색끼가 있음.)
- [x] 캐릭터 상세 뷰에서 캐릭터 이름, 한줄 설명 있는 라벨 위/아래 패딩 같게 조정
- [x] 캐릭터 상세 뷰에서 캐릭터 모션 라벨 옆의 아이콘 최신화
