### ISSUE TITLE
[Fix] 온보딩 약관동의 뷰 개선

### ISSUE THREAD

**Issue by Johyerin** [Team-Offroad/Offroad-iOS#367]
## 🔥 Issue 내용
온보딩 약관동의 뷰 개선

## ✅ To-do
- [x] 팝업 로딩 시점이 상이한 문제 해결
- [x] 화면 전환 뷰 수정
- [x] 마케팅 수신 동의 토스트 구현
