### ISSUE TITLE
[Fix] 채팅 로그 뷰 개선, 무한스크롤 로딩 로티 개선

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#375]
## 🔥 Issue 내용
채팅 로그 뷰에서 발생하는 문제들을 수정하기 위함
## ✅ To-do
- [x] 무한스크롤 로딩 로티 개선
현재 `UIScrollView`에 확장으로 구현된 메서드가 있는데, `UIScrollView`의 확장보다 `UIScrollView`에서 채택할 수 있는 프로토콜을 만들어서 이를 채택한 커스텀 UICollectionView를 만드는 방안 고려.
- [x] 채팅 로그 뷰에서 무한스크롤 작동 조건 개선
- [x] 채팅 로그 뷰에서 빠르게 스크롤하거나, 화면 상단 상태바를 누를 경우, 연속적으로 무한스크롤 데이터를 불러와 이상하게 보이는 문제 해결
(이슈 작성 시점 기준으로, 아직 승인되지 않은 PR의 변경 내용 기준)
