### ISSUE TITLE
[Fix] 캐릭터 채팅창 관련 기능, 로직 수정

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#385]
## 🔥 Issue 내용
캐릭터 채팅창 관련 기능 수정
## ✅ To-do
- [x] 현재 캐릭터 채팅 창에서 답장하기 버튼이 있는 경우에 한해서 채팅을 탭 하면 채팅 로그로 이동하도록 되어있는데, 
답장하기 버튼이 없는 경우에도 탭 시 채팅 로그로 이동하도록 구현
- [x] 캐릭터 채팅 창 줄 수 제한
- [x] 캐릭터 채팅 창 chevron 버튼 탭 영역 확장
- ~캐릭터 채팅 창 chevron 버튼 1줄일 때 숨기기~
-> 후순위로 변경
- [x] 캐릭터 채팅 창 터치 피드백 구현
채팅 창, chevron 버튼 둘 다
- [x] CharacterChatManager의 생성자에서 채팅창, 채팅 입력창 숨기도록 구현
- [x] setupAdditionalLayout() 메서드에 mode 매개변수 추가하기
- [x] 모드 변경 시 레이아웃 변경 코드 정리(view controller의 코드 chatBox 안으로 이동 및 view controller에서 재활용)
- [ ] 채팅 로그 뷰를 보고 있을 때 선톡이 오는 경우 고려하여 개선하기
  - 채팅 로그뷰를 보고 있을 때 선톡이 오는 경우
  - ~마지막으로 보던 뷰가 채팅 로그 뷰일 경우 푸시 알림을 눌러서 앱에 진입하면?~
  -> 홈 화면으로 이동해서 문제 없음
- [x] 홈 뷰에서 메시지 버튼(채팅 버튼) 옆의 빨간 점이 없는 상태에서 캐릭터 선톡이 오면?
  - 빨간 점이 생겨야 한다. "답장하기" 버튼을 누르거나 채팅 로그 뷰로 이동하면 빨간 점은 사라진다. 
  - 만약 사용자가 "답장하기" 버튼을 누르지 않거나, 채팅 로그 뷰로 이동하지 않는다면
  (채팅창이 사라지게 놔두거나, 채팅 메시지를 직접 위로 올려서 없앤다면)
  빨간 점이 남아있어야 한다. 
- ~캐릭터 채팅 박스 숨길 때 애니메이션 적용 여부 선택할 수 있도록 변경
(기존 채팅이 떠 있을 때 새 채팅이 오려면 기존 채팅을 숨겨야 하는데, 이때 바로 숨길 수 있도록)
-> 후순위로 변경
- [x] ORBAlertController의 textField로 인해 키보드 올라왔을 때 캐릭터 선톡이 오면 이상하게 동작하는 현상
- [x] 채팅 입력창 흰색 테두리 주변으로 그림자 넣기
- [ ] 캐릭터 선톡 3초 뒤에 사라지도록 구현
- [x] 캐릭터 채팅 박스 내리는 제스처 중 채팅 종료 눌렀을 때 panGestureRecognizer가 여전히 인식되는 문제

그 외 기타
- [x] 채팅 로그에서 채팅 버블 보내는 애니메이션 개선(애니메이션 시작 시점 변경)
