### ISSUE TITLE
[Fix] 온보딩 2차 QA 수정사항 적용

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#387]
## ✅ To-do
- [x] 중복 textfield layer 색상 변화
- [x] 성별 뷰에서 backbutton 클릭 시 기존 값 reset
- [x] 캐릭터 선택 뷰에서 backbutton 클릭 시 기존 값 reset -> _executePop 어디?_
- [x] 캐릭터 선택 뷰에서 patch 요청 보내도록 수정
- [ ] 닉네임 뷰 textfield 마지막 글자 종성 처리
