### ISSUE TITLE
[Fix] 3차 QA 수정사항 적용

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#398]
## ✅ To-do
- [x] 닉네임 뷰 formError가 아닌 닉네임일 때 중복 버튼 누르기 전엔 에러메세지가 사라지는 게 아니라 "*한글 2~8자, 영어 2~16자 이내로 작성해주세요."가 뜨도록 수정
- [x] 닉네임 뷰 hintText "닉네임을 입력" -> "닉네임 입력"으로 수정
- [x] 닉네임 뷰 layer 색상 초기 상태의 경우(`isTextFieldEmpty && isInitialState`)와 값을 지워서 `isTextFieldEmpty`인 상황을 분리
- [x] 중복 닉네임일 때의 layer 색상 변경
- [x] 성별 뷰 눌렀다 해제 가능하게 수정
