### ISSUE TITLE
[Fix] QA 수정사항 반영

### ISSUE THREAD

**Issue by nolanMinsung** [Team-Offroad/Offroad-iOS#405]
## 🔥 Issue 내용
QA 수정사항
## ✅ To-do
- [x] 획득 캐릭터 목록 뷰에서 제목 옆의 이미지 변경
- [x] 칭호 변경 후 마이페이지에서 칭호 변경
- [x] 지도 툴팁 X버튼 눌렀을 때 더미데이터로 캐릭터 선톡 오는 동작 제거
