### ISSUE TITLE
[Fix] 3차 QA 수정사항 반영

### ISSUE THREAD

**Issue by Johyerin** [Team-Offroad/Offroad-iOS#409]
## 🔥 Issue 내용
3차 QA 수정사항 반영

## ✅ To-do
- [x] 홈화면 채팅버튼 이미지 변경
- [x] 캐릭터 선택 뷰 앱 크래시 현상 해결
- [x] 추가적인 색상이나 이미지 싱크
