### ISSUE TITLE
[Feat] 캐릭터 선택 뷰 API 연결

### ISSUE THREAD

**Issue by Johyerin** [Team-Offroad/Offroad-iOS#65]
## 🔥 Issue 내용
캐릭터 선택 뷰 API 연결

## ✅ To-do
- [ ] 캐릭터 조회 API
- [ ] 캐릭터 선택 API
- [ ] 선택 완료 캐릭터 호출 API
