### ISSUE TITLE
[Feat] 닉네임, 생년월일, 성별 선택 정보 POST 네트워크 통신

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#67]
## 🔥 Issue 내용
유저가 회원가입 시 닉네임, 생년월일, 성별을 작성하는데 이때의 정보를 서버에 POST하는 네트워크 통신이다.
## ✅ To-do
- [ ] 닉네임 정보 전달
- [ ] 생년월일 정보 전달
- [ ] 성별 선택 정보 전달
- [ ] 정보들 총합해서 서버에 POST
