### ISSUE TITLE
[Chore] 프로필 업데이트 뷰 수정사항 반영

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#72]
## 🔥 Issue 내용
프로필 업데이트 뷰에서 QA 대비 자잘한 수정사항 적용
## ✅ To-do
- [x] 닉네임 입력 뷰에서 버튼 길이 고정
- [x] 닉네임 입력 뷰 텍스트필드 글자 수 제한 및 백스페이스 처리
- [x] 텍스트필드 지우면 layer 색상 계속 주황색인거 수정 -> BirthVC에도 적용
- [x] 생년월일 입력 뷰에서 textColor 지정
- [ ] 이미지뷰 contentMode
- [ ] 나이 1900년 이상, 1~12월, 1~31일이 아닐 시 에러 처리
- [x] 건너뛰기 기능 구현
- [x] 건너뛰기 가능한 View에 null값 가능하도록 구현
- [x] 정규식으로 중복이 아닐 때 닉네임 형식 오류 처리, 중복이 아니고 형식오류 아니면 버튼 활성화
