### ISSUE TITLE
[Feat] 네비게이션 바 커스텀

### ISSUE THREAD

**Issue by codeJiwon** [Team-Offroad/Offroad-iOS#83]
## 🔥 Issue 내용
네비게이션 바의 뒤로가기 버튼을 피그마 디자인대로 수정해야한다. 
따라서 현 네비게이션바를 setNavigationBarHidden으로 바꾸고 UIView를 만든 후 레이아웃 피그마대로 설정
## ✅ To-do
- [ ] 투명한 UIView 생성
- [ ] 기존에 있던 "건너뛰기" 버튼 옮기기
- [ ] 뒤로가기 버튼 커스텀
